开始训练...
训练集数据处理。。。。
=============
验证集数据处理。。。。。
=============
0
epoch: 0, batch_id: 0, loss is：0.7170
epoch: 0, batch_id: 10, loss is：0.6714
[validation] accuracy 0.6250, loss 0.6610
1
epoch: 1, batch_id: 0, loss is：0.6649
epoch: 1, batch_id: 10, loss is：0.6697
[validation] accuracy 0.6250, loss 0.6560
2
epoch: 2, batch_id: 0, loss is：0.6604
epoch: 2, batch_id: 10, loss is：0.6573
[validation] accuracy 0.6250, loss 0.6463
3
epoch: 3, batch_id: 0, loss is：0.6477
epoch: 3, batch_id: 10, loss is：0.6496
[validation] accuracy 0.6250, loss 0.6331
4
epoch: 4, batch_id: 0, loss is：0.6330
epoch: 4, batch_id: 10, loss is：0.6420
[validation] accuracy 0.6250, loss 0.6219
D:\Users\Admin\Python37\lib\site-packages\paddle\nn\layer\norm.py:641: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
开始训练...
训练集数据处理。。。。
=============
验证集数据处理。。。。。
=============
0
D:\Users\Admin\Python37\lib\site-packages\paddle\nn\layer\norm.py:641: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
Traceback (most recent call last):
  File "D:/Users/Admin/PycharmProjects/PyCharm_Projects/Deep_learning/cat_dog/model_training02.py", line 107, in <module>
    train(model, EPOCH_NLM, opt)
  File "D:/Users/Admin/PycharmProjects/PyCharm_Projects/Deep_learning/cat_dog/model_training02.py", line 37, in train
    logits = model(img)
  File "D:\Users\Admin\Python37\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Users\Admin\PycharmProjects\PyCharm_Projects\Deep_learning\cat_dog\LeNet.py", line 56, in forward
    x = self.fc1(x)  # 线性层
  File "D:\Users\Admin\Python37\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Users\Admin\Python37\lib\site-packages\paddle\nn\layer\common.py", line 129, in forward
    x=input, weight=self.weight, bias=self.bias, name=self.name)
  File "D:\Users\Admin\Python37\lib\site-packages\paddle\nn\functional\common.py", line 1451, in linear
    'transpose_Y', False, "alpha", 1)
ValueError: (InvalidArgument) Input X's width should be equal to the Y's height, but received X's shape: [10, 26450], Y's shape: [16200, 64].
  [Hint: Expected mat_dim_x.width_ == mat_dim_y.height_, but received mat_dim_x.width_:26450 != mat_dim_y.height_:16200.] (at C:/home/workspace/Paddle_release/paddle/fluid/operators/matmul_op.cc:594)
  [operator < matmul > error]
